import numpy as np

# Defining the type of each columns reduces the memory space used by the DataFrame
types = {
    'FECHA_ACTUALIZACION': 'object',
    'ID_REGISTRO': 'object',
    'ORIGEN': np.int8,
    'SECTOR': np.int8,
    'ENTIDAD_UM': np.int8,
    'SEXO': np.int8,
    'ENTIDAD_NAC': np.int8,
    'ENTIDAD_RES': np.int8,
    'MUNICIPIO_RES': np.int16,
    'TIPO_PACIENTE': np.int8,
    'FECHA_INGRESO': 'object',
    'FECHA_SINTOMAS': 'object',
    'FECHA_DEF': 'object',
    'INTUBADO': np.int8,
    'NEUMONIA': np.int8,
    'EDAD': np.int16,
    'NACIONALIDAD': np.int8,
    'EMBARAZO': np.int8,
    'HABLA_LENGUA_INDIG': np.int8,
    'INDIGENA': np.int8,
    'DIABETES': np.int8,
    'EPOC': np.int8,
    'ASMA': np.int8,
    'INMUSUPR': np.int8,
    'HIPERTENSION':np.int8,
    'OTRA_COM': np.int8,
    'CARDIOVASCULAR': np.int8,
    'OBESIDAD': np.int8,
    'RENAL_CRONICA': np.int8,
    'TABAQUISMO': np.int8,
    'OTRO_CASO': np.int8,
    'TOMA_MUESTRA_LAB': np.int8,
    'RESULTADO_LAB': np.int8,
    'TOMA_MUESTRA_ANTIGENO': np.int8,
    'RESULTADO_ANTIGENO': np.int8,
    'CLASIFICACION_FINAL': np.int8,
    'MIGRANTE': np.int8,
    'PAIS_NACIONALIDAD': 'object',
    'PAIS_ORIGEN': 'object',
    'UCI': np.int8
}